import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
    title: 'Terms of Service | JSON to Model',
    description: 'Terms of Service for jsontomodel.com',
};

export default function TermsOfService() {
    return (
        <main className="mx-auto max-w-3xl px-6 py-20 min-h-[70vh]">
            <h1 className="mb-8 font-headline text-4xl font-bold tracking-tight">Terms of Service</h1>

            <div className="prose prose-slate dark:prose-invert max-w-none space-y-6">
                <p className="text-muted-foreground">Last Updated: {new Date("2026-02-26").toLocaleDateString()}</p>

                <section>
                    <h2 className="text-2xl font-bold mt-8 mb-4">1. Acceptance of Terms</h2>
                    <p>
                        By accessing and using jsontomodel.com (the "Service"), you accept and agree to be bound by the terms and provision of this agreement.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold mt-8 mb-4">2. Description of Service</h2>
                    <p>
                        JSON to Model provides a free, web-based utility for developers to generate programming language models, classes, and structs from JSON data. The Service is provided "AS IS" and on an "AS AVAILABLE" basis.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold mt-8 mb-4">3. Data Privacy</h2>
                    <p>
                        As outlined in our <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>, the core functionality of the Service operates locally within your web browser. We do not transmit or store the JSON payloads you paste into the tool.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold mt-8 mb-4">4. Limitations of Liability</h2>
                    <p>
                        In no event shall JSON to Model, its creators, or partners be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any bugs, errors, or inaccuracies in the generated code; or (iii) any unauthorized access, use or alteration of your transmissions or content.
                    </p>
                    <p><strong>Disclaimer:</strong> You are solely responsible for reviewing and testing the code generated by this tool before using it in any production environment.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold mt-8 mb-4">5. Intellectual Property</h2>
                    <p>
                        You retain full ownership and intellectual property rights to any JSON data you input and any code you generate using the Service. We claim no ownership over the input or output.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold mt-8 mb-4">6. Changes to Terms</h2>
                    <p>
                        We reserve the right, at our sole discretion, to modify or replace these Terms at any time. What constitutes a material change will be determined at our sole discretion.
                    </p>
                </section>
            </div>
        </main>
    );
}
